services:
  db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-messaging_app}
      MYSQL_USER: ${MYSQL_USER:-Anastansia}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Herod@7915}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Herod@7915}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    # (optional) expose MySQL to host tools:
    # ports:
    #   - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Django
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-1}
      # DB (web reads from env; db service uses MYSQL_* above)
      DB_NAME: ${MYSQL_DB:-messaging_app}
      DB_USER: ${MYSQL_USER:-Anastansia}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Herod@7915}
      DB_HOST: db
      DB_PORT: "3306"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
